# -*- coding: utf-8 -*-
"""Untitled85.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1ALPH4PVwJG3aXSQwx6J1BdXiL0ANG1
"""

import streamlit as st
import numpy as np
from PIL import Image
import joblib
import matplotlib.pyplot as plt
from utils import preprocess_image, predict_digit

# Load trained model
model = joblib.load("mnist_model.pkl")

st.title("🖊️ Handwritten Digit Recognizer")
st.write("Upload an image of a handwritten digit (28x28 grayscale). The model will predict the digit.")

uploaded_file = st.file_uploader("Choose an image...", type=["png", "jpg", "jpeg"])

if uploaded_file:
    image = Image.open(uploaded_file).convert("L")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    with open("temp_image.png", "wb") as f:
        f.write(uploaded_file.read())

    processed = preprocess_image("temp_image.png")
    prediction = predict_digit(processed, model)

    st.subheader(f"🔢 Predicted Digit: {prediction}")